### ISSUE TITLE
Fix Time And Date

### ISSUE THREAD

**Issue by RAJAGOPALAN-GANGADHARAN** [NJACKWinterOfCode/JS-OS#10]
1) Replace the clock app with cool clock.
2)Date and time not properly aligned( Microsoft Edge Dev) not sure about chrome, But time and date placements need changes.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN Yes, due to some reason the date in line 2 is not aligned properly. 
Please clarify point 1, should we improve the current clock or do we require a new clock made from scratch ?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Currently the clock app is funny, I just copy pasted code from somewhere. Half of window is white and when we increase size of window it keeps getting bigger. Also the camera is looking too traditional. It would be nice if there is awesome looking camera.

**Comment by ankushbhardwxj** [comment]
Okay , I am making a PR for the point 2. I just corrected it, was just some CSS issue.
I will need some time for Clock App so i will make another PR for it.

**Comment by ankushbhardwxj** [comment]
>  Also the camera is looking too traditional. It would be nice if there is awesome looking camera.

Where's the camera ? I cannot find it.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Sorry i meant clock 😅

**Comment by ankingcodes** [comment]
Okay, I would create the most fancy clock possible 💯 tonight !!

**Comment by ankingcodes** [comment]
@RAJAGOPALAN-GANGADHARAN could you point me to the file in which the `TimeApp` component is put inside the `Window` component. I couldn't find it.

**Comment by ankushbhardwxj** [comment]
![JS-OS-GoogleChrome2019-12-0719-5](https://user-images.githubusercontent.com/40923324/70376416-e20e4f00-192e-11ea-9df7-74a6fa2c4736.gif)

@RAJAGOPALAN-GANGADHARAN what do you think about this ? Looks amazing doesn't it ? Do you wanna change the background color ?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Looks awesome! But Im currently busy so please expect delay in my replies.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Probably we can implement color changes when we have fs support. So for now it looks cool
