### ISSUE TITLE
Commands for Terminal

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#13]
Key deliveries : 

- [x] `tree` command
- [x] `ls` command
- [ ] `cd` command
- [x] `cat` command
- [ ] `mkdir` command

We need to make a command line parser that can execute the above mentioned commands.
It is important for these commands to interact with the  filesystem `fs.json` created.
Hopefully, this issue will solve #3

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I'd be implementing these soon.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Awesome man eagerly waiting and as a gift would add 2 points for opening this issue and will add 15 more for that pr u made.
