### ISSUE TITLE
ToDo App

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#19]
A ToDo app is an essential app in every OS. We require a ToDo App capable of doing CRUD operations.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I'm working on it 👍 
Let me know your thoughts

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Awesome Great will add points for this.
