### ISSUE TITLE
Code Editor

### ISSUE THREAD

**Issue by RAJAGOPALAN-GANGADHARAN** [NJACKWinterOfCode/JS-OS#2]
Code Editor uses Mono Engine(from vscode) try making it full fledged editor by adding menus and other things.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN What would be the uses of this editor ? Making `.txt` files ? Writing code ? If so , how do you plan to execute the code that is written ?

**Comment by Saifu0** [comment]
Hy @RAJAGOPALAN-GANGADHARAN , I am a beginner in open source. Please help me to solve any issue that will be appropriate for me. BTW, I know React that's why I am asking for this project.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hey its great to hear. So the os has a editor which a notepad kind of icon if you click the launcher. So I am using Monaco editor as the code editor u can look up Google for more info on Monaco editor. The text editor doesn't anything for now. I want you to add menus, language support (apis available), probably use vs code for inspiration. As far as saving a text file is considered we need to fix the file system first to have a common representation throughout the entire os. Let me know if you have any questions.

**Comment by Saifu0** [comment]
@RAJAGOPALAN-GANGADHARAN Can I use default html tags as input ?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
You should look at monaco in react. This is the code where it is used. https://github.com/NJACKWinterOfCode/JS-OS/blob/master/src/defaultapps/texteditor/editor.js

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I was thinking of adding menu for saving a file along with contents but I haven't worked with Monaco before. Can you point me some documentation that shows how we can implement menus etc..

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hey, it’s a great idea. So Monaco doesn’t have any native menu system. Hence you could create a menu bar on top and try to attach functionality to it. Like save to write to our fs. Change language etc. 
 You could refer this for what is possible with the react component and create an interface for it https://www.npmjs.com/package/@monaco-editor/react
