### ISSUE TITLE
Improve app launcher

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#20]
Currently, when we open app launcher, we need to click a small 'X' at the top-left of the screen to close it which is not a good UX. So, lets change it so that we can close app launcher on a click anywhere on the screen.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I am working on it 👍

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
That's a wonderful addition go ahead 👍
