### ISSUE TITLE
Calculator App

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#23]
An OS is always incomplete without a Calculator app. Let's create a calculator app for JS-OS

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I'll get this done 👍

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Ofcourse Cool one. Also I am going to update the editor. It seems i havent used monaco. Hang on

**Comment by ankushbhardwxj** [comment]
Cool! I have some ideas too for the editor. Will work on it soon 💯

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Could you rebase changes before commiting, cause I have updated the editor.

**Comment by ankushbhardwxj** [comment]
you updated editor on this branch(NJACK one) ??

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
well in the parent one
set ur upstream to my repo RAJAGOPALAN-GANGADHARAN/JS-OS and fetch and rebase

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Did few more changes please rebase now

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Also FileSystem is more prioritized could you try fixing it thanks.

**Comment by ankushbhardwxj** [comment]
I dont know why but the monaco code update has broken the code, 
![Capture](https://user-images.githubusercontent.com/40923324/71267913-bd27cc00-2371-11ea-94e4-36281ee2e538.PNG)
@RAJAGOPALAN-GANGADHARAN please look into this issue

**Comment by ankushbhardwxj** [comment]
BTW, the calculator is ready. Let me know when you fix this so that I can make a PR.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Delete the package-lock and try doing npm install again.

**Comment by ankushbhardwxj** [comment]
did it , got the same problem

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Works fine on windows are you using WSL? try on windows maybe

**Comment by ankushbhardwxj** [comment]
I'm on WSL

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Yes npm for WSL is pain. Try using bare windows it should work fine.

**Comment by ankushbhardwxj** [comment]
I swear windows is crazy. I just restarted the computer and ran npm install and it ran perfectly.
However on npm start it gives error.

**Comment by ankushbhardwxj** [comment]
I think you missed to add a dependency `monaco-editor-webpack-plugin`. As soon as I installed that , everything worked. 👍
