### ISSUE TITLE
Modify `ls` && `tree` commands

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#26]
The current implementation of the commands is to get the files from a local `fs.json` file which is now deprecated since we are using a server & database now as a filesystem. 
After #25 is merged, we can modify the commands to perform a GET request from the API.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I have started work on this 👍 . Please merge the PR so that I can complete this soon.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Sorry I had some work, Will review it tomorrow. Thanks
