### ISSUE TITLE
Make singular command for App

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#28]
Currently, we have to `npm start` for client and `npm start` for server. We need a single command like `npm run dev` that would start both client and server.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I'd get this done 👍

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Yes thats great would love to see the entire things in action.
