### ISSUE TITLE
mkdir && touch commands for terminal

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#29]
Currently we have `ls` & `tree` commands to view files & directories from the filesystem. Now, we create commands `mkdir` & `touch` to create directories and files respectively.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I'll work on this 👍

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Thats really wonderful.
