### ISSUE TITLE
integrate file explorer to filesystem 

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#32]
The file explorer currently displays random documents and folders. We need to merge it to the existing filesystem.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I'll be working on this 👍

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Wonderful is it done yet?

**Comment by ankushbhardwxj** [comment]
Will be done today :+1:

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN did u add points for that PR you merged ? My score didn't update

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
done have fun

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN the code of the file explorer you implemented is really hard to understand, do you mind if I reset it and write it from scratch ?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Sure bro whatever you find easier. Do make pr in a seperate branch thanks.

**Comment by ankushbhardwxj** [comment]
Of course. I made 2 PR for the terminal, check out 🔨
