### ISSUE TITLE
Front-End of Calculator and problems in it's functioning

### ISSUE THREAD

**Issue by Vishalghyv** [NJACKWinterOfCode/JS-OS#33]
For FrontEnd - 
      Main screen have error in background

For It's functioning-
1. History function not working
2. Current display of processed values is not correct
3. Pressing numbers on keyboard doesn't have any use

**Comment by Vishalghyv** [comment]
I will be working on this

**Comment by Vishalghyv** [comment]
Should I use react-key-handler for keypressing?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
The ideas are awesome man. Once done please post a gif of the working feature so I could verify it. thanks.

**Comment by ankushbhardwxj** [comment]
I dont think you need react-key-handler ( a package ) for this functionality. Just add keyhandlers to the current implementation 👍

**Comment by Vishalghyv** [comment]
@ankingcodes @RAJAGOPALAN-GANGADHARAN Changed frontend and updated keyevents, i think this issue is solved, hope my commits don't cause problem.I really liked this project and would be wiling to work on this further if there is anything i could help

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hello @Vishalghyv happy to hear it. When you make a pr please do make a gif so i can see how its working.looking forward for ur contributions
