### ISSUE TITLE
Issue related to UI

### ISSUE THREAD

**Issue by sk044** [NJACKWinterOfCode/JS-OS#35]
The task bar can be improved ..... and the size of new window opened is quite small ..and is incovinient to use at starting...

**Comment by ankushbhardwxj** [comment]
I had earlier modified the window size. May I know using which app caused this inconvenience?

**Comment by sk044** [comment]
The clock ..size and the notes ...
Is the current website which is mentioned at the start is updated..???

**Comment by ankushbhardwxj** [comment]
Oh, the current website links to the original repo and is not the updated version.

**Comment by ankushbhardwxj** [comment]
In the local one, This issue has been fixed. You may close this issue if you like 👍

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@sk044 the web version is pretty outdated. if you see branch gh-pages is way behind the master branch. So first get the gh-pages branch up to date. Then make sure the app works perfectly in gh-pages. Thanks.
