### ISSUE TITLE
Needs to update readme

### ISSUE THREAD

**Issue by sgpritam** [NJACKWinterOfCode/JS-OS#4]
needs to update readme for git contribution

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Sure you can fix it if you want I'll add points for it. For now the bare minimum details to run it are present. Feel free to add more

**Comment by sgpritam** [comment]
Okay i would like to work on it

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Great let me know if you need any details.

**Comment by sgpritam** [comment]
Which technology is used inside the project

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
ReactJS

**Comment by sgpritam** [comment]
Please review

**Comment by sgpritam** [comment]
Please label my issues

**Comment by sgpritam** [comment]
Please label my issues and update the marks
