### ISSUE TITLE
Add functionality to the new and delete button

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#41]
The file explorer has two buttons for create and delete file but have no functionality. So we need to add functionality to them.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I'm on it 👍

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Awesome waiting for it ❤️ . Also Im busy till 6th Jan after that ill also do some work on this os if ur sticking around. Thanks

**Comment by ankushbhardwxj** [comment]
Its okay man. 
This NWOC is gonna be over by 6th. 
Please merge my PRs when you get notified.
After NWOC, I'm open for new ideas for this OS 👍

**Comment by ankushbhardwxj** [comment]
I'm trying to get most of the stuff done, so that later on all you can focus on is to improve , refactor and have it in a stable state.
