### ISSUE TITLE
Clean up Codebase

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#49]
Currently the codebase is very unsystematic, has reduntant/deprecated files & random code. So we need to remove redundant files, perform linting by integrating `eslint` and do other minor fixes.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I'm going to conclude my work by doing some cleanup. Working on this right now 👍 
NWoC was a great experience. Hope you had fun collaborating with me

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Haha thanks. I had lot of fun working with you too, and your always welcome to contribute after NWOC 😉 . I can make you a collaborator if you are interested. Best of luck on your future endeavors.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN  I'd love to improve this project further. You may add me as a collaborator. I'd like to show off this project too. Thanks 🥇
