### ISSUE TITLE
Improve code

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#5]
![JS-OS issue](https://user-images.githubusercontent.com/40923324/70302052-10eacf00-1822-11ea-8958-6aa55da513ed.PNG)

@RAJAGOPALAN-GANGADHARAN I think we need to get rid of these warnings and try to refactor the code that is already written, before writing new code. If you agree, I can start working on it. 
Also, a lot of packages are deprecated so I believe we should update them too. However, this can be done in another issue. Let me know what you think.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hey, true it's been long time since I updated the packages
So first things first--update the node packages to their latest versions.
I decided to write things module wise, so see if you could make it more clean.
And as always I'm open to any suggestions.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN please add a label to this, so that I can get points for NWOC
