### ISSUE TITLE
Redesign the Terminal

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/JS-OS#8]
The current implementation of the terminal is not efficient considering the future goals of the project. We need to redesign the terminal to make it look more realistic to a bash terminal.
 Various functions need to be defined so that we can use JS defined bash commands efficiently.
 Methods for `keypress` and `input` actions should be prepared.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN Please acknowledge this issue and give your thoughts. I'm currently working on it. This would be important for #3

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Sure that would be really great. GO ahead.
